apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: nrkapri/customer-service:0.1.0
        ports:
        - containerPort: 8080
        env:
        - name: WELCOME_STRING
          valueFrom:
            configMapKeyRef:
              name: customer-service
              key: welcome-string