apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: second-service
spec:
 selector:
  matchLabels:
   app: second-service
 replicas: 3
 template:
   metadata:
     labels:
       app: second-service
   spec:
     containers:
     - name: second-service
       image: nrkapri/second-service:0.1.0
       ports:
       - containerPort: 8080
         name: server
