apiVersion: v1
kind: Service
metadata:
  name: second-service
spec:
  type: LoadBalancer
  ports:
   - name: second-service-port
     port: 8080
     targetPort: 8080
     nodePort: 30083
  selector:
    app: second-service