apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  type: LoadBalancer
  ports:
   - name: first-service-port
     port: 8080
     targetPort: 8080
     nodePort: 30082
  selector:
    app: first-service